# Site settings
title: The Grokery Blog
description: > # this means to ignore newlines until "baseurl:"
  FIXME: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lauervose.com" # the base hostname & protocol for your site

authors:
  chuck:
    name: Chuck Lauer Vose
    email: vosechu@gmail.com
  erica:
    name: Erica Lauer Vose
    email: elauervose@gmail.com

cat_map:
  tech:
    name: Tech Topics
    url: /tech.html
  code-challenge:
    name: Code Challenges
    url: /code-challenges.html
  tutorial:
    name: Tutorials
    url: /tutorials.html
  professional:
    name: Professional Skills
    url: /professional.html

# Build settings
markdown: kramdown
